### ISSUE TITLE
Engineers can manage any user's groups

### ISSUE THREAD

**Issue by kraney** [coinbase/self-service-iam#1]
I notice that the policy "AllowEngineeringToAddSubUsersToServiceGroups" actually allows engineering to add ANY user to the service groups. I dug around in AWS docs but couldn't find any condition variable that could be set to restrict it to subusers. Is it even possible to do so?

Attach / Detach user policy calls, in contrast, have a "iam:PolicyArn" variable you can reference in a condition to avoid this.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
